version: '3'
services:
  db:
    image: 'postgres:latest'
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  aprrka:
    restart: always
    build: .
    depends_on:
      - db
